### ISSUE TITLE
Access to the repo

### ISSUE THREAD

**Issue by andersonresende** [fixmydjango/fixmydjango#30]
@renatooliveira could you give me access to make PRs directly?

**Comment by fjsj** [comment]
@filipeximenes should add you to the org: https://github.com/orgs/fixmydjango/people

also, I guess he should make PRs publicly accessible for everyone

**Comment by filipeximenes** [comment]
Just gave access. Aren't PRs public already?

**Comment by andersonresende** [comment]
origin	git@github.com:fixmydjango/fixmydjango.git (fetch)
origin	git@github.com:fixmydjango/fixmydjango.git (push)

I still don't have access to push a branch.

**Comment by filipeximenes** [comment]
Fixed
