### ISSUE TITLE
Add ability to reply comments

### ISSUE THREAD

**Issue by renatooliveira** [fixmydjango/fixmydjango#36]
We'll do facebook like. It's easy to read, rather than Django project style.

**Comment by filipeximenes** [comment]
@renatooliveira so you want to allow multiple threads rather a single one?
I think we should keep it simple. I don't like the idea of having multiple threads. Discussions will run around a single issue, so I don't think it will be good to have people replying to a comment. Better to keep a single discussion "forum like".

**Comment by renatooliveira** [comment]
yeah, makes sense. Closing
